CREATE TABLE IF NOT EXISTS scheduled_tasks (
    task_name VARCHAR(100) COMMENT '任务名称',
    task_instance VARCHAR(100) COMMENT '任务实例',
    task_data LONGBLOB COMMENT '任务数据',
    execution_time TIMESTAMP COMMENT '执行时间',
    picked BIT COMMENT '是否已被提取',
    picked_by VARCHAR(50) COMMENT '提取者',
    last_success TIMESTAMP COMMENT '最后成功时间',
    last_failure TIMESTAMP COMMENT '最后失败时间',
    consecutive_failures INT COMMENT '连续失败次数',
    last_heartbeat TIMESTAMP COMMENT '最后心跳时间',
    version BIGINT COMMENT '版本',
    PRIMARY KEY (task_name, task_instance)
) COMMENT='定时任务表';


CREATE TABLE IF NOT EXISTS job_queue (
    `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
    `delete_manager` BIGINT COMMENT '删除的人',
    `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
    `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
    `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
    `field_id` VARCHAR(255) COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
    `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
    `id` BIGINT COMMENT '唯一ID号',
    `field_prop` VARCHAR(255) COMMENT '字段属性',
    `add_time` DATETIME COMMENT '添加时间',
    `delete_time` DATETIME COMMENT '删除时间',
    `has_status` INT COMMENT '状态(0启用|1禁用)',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
    `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
    `job_name` VARCHAR(255) NOT NULL COMMENT '转移名称',
    `job_id` BIGINT COMMENT '任务ID',
    `job_data` VARCHAR(255) COMMENT '转移数据',
    `status` VARCHAR(255) COMMENT '状态',
    `step` INT COMMENT '当前执行到的步骤',
    PRIMARY KEY (`id`)
)COMMENT='任务队列表';

CREATE TABLE IF NOT EXISTS job (
    `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
    `delete_manager` BIGINT COMMENT '删除的人',
    `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
    `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
    `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
    `field_id` VARCHAR(255) COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
    `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
    `id` BIGINT COMMENT '唯一ID号',
    `field_prop` VARCHAR(255) COMMENT '字段属性',
    `add_time` DATETIME COMMENT '添加时间',
    `delete_time` DATETIME COMMENT '删除时间',
    `has_status` INT COMMENT '状态(0启用|1禁用)',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
    `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
    `trans_ids` VARCHAR(255) COMMENT '关联的转换任务id',
    `git_id` VARCHAR(255) COMMENT '仓库名称',
    `relative_location` VARCHAR(255) COMMENT '作业文件路径',
    `job_context` LONGTEXT COMMENT '任务的上下文',
    `name` VARCHAR(255) COMMENT '名称',
    `description` VARCHAR(255) COMMENT '描述',
    `type` VARCHAR(255) COMMENT '类型',
    `path` VARCHAR(255) COMMENT '路径',
    `quartz` VARCHAR(255) COMMENT 'Quartz',
    `strategy` VARCHAR(255) COMMENT '同步策略',
    `log_level` VARCHAR(255) COMMENT '日志级别',
    `status` VARCHAR(10)  COMMENT '状态',
    `category_id` VARCHAR(255) COMMENT '分类ID'
) COMMENT='任务表';


CREATE TABLE IF NOT EXISTS trans (
    `has_delete` INT COMMENT '是否删除(1删除|0正常|null正常)',
    `delete_manager` BIGINT COMMENT '删除的人',
    `application_id` BIGINT COMMENT '所属应用 应用权限: 只能看到所属应用的权限【默认】',
    `application_name` VARCHAR(64) COMMENT '应用名称，唯一性，用于做应用标识【最好与springboot的application.name对应】',
    `tenant_id` BIGINT COMMENT '所属租户 , 租户权限',
    `field_id` VARCHAR(255) COMMENT '字段权限：部分字段权限无法加密或者不显示，或者大于某个值',
    `department_id` BIGINT COMMENT '部门权限: 只能看到自己所在部门的数据',
    `id` BIGINT COMMENT '唯一ID号',
    `field_prop` VARCHAR(255) COMMENT '字段属性',
    `add_time` DATETIME COMMENT '添加时间',
    `delete_time` DATETIME COMMENT '删除时间',
    `has_status` INT COMMENT '状态(0启用|1禁用)',
    `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `operator_id` BIGINT COMMENT '操作员 用户权限: 只能看到自己操作的数据',
    `last_update_operator_id` BIGINT COMMENT '最后更新操作员 用户权限: 只能看到自己操作的数据',
    `git_id` VARCHAR(255) COMMENT '仓库名称',
    `relative_location` VARCHAR(255) COMMENT '转换文件路径',
    `trans_context` LONGTEXT COMMENT '任务的上下文',
    `job_id` BIGINT COMMENT '关联的任务id',
    `order_step` INT COMMENT '任务排序',
    `name` VARCHAR(255) COMMENT '名称',
    `description` VARCHAR(255) COMMENT '描述',
    `type` VARCHAR(255) COMMENT '类型',
    `path` VARCHAR(255) COMMENT '路径',
    `quartz` VARCHAR(255) COMMENT 'Quartz',
    `strategy` VARCHAR(255) COMMENT '同步策略',
    `log_level` VARCHAR(255) COMMENT '日志级别',
    `status` VARCHAR(10) COMMENT '状态',
    `category_id` VARCHAR(255) COMMENT '分类ID'
) COMMENT='数据转换表';
